name: 'dbt_dw'
version: '1.0.0'

profile: 'dbt_dw'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
  "dbt_date:time_zone": "America/Sao_Paulo"

clean-targets:        

models:
  dbt_dw:
    staging:
      +materialized: view
    
    intermediate:
      +materialized: table
    
    mart:
      +materialized: table